### ISSUE TITLE
Steering committee vote: add slsa-jenkins-generator to the slsa-framework organisation

### ISSUE THREAD

**Issue by joshuagl** [slsa-framework/governance#18]
Samsung would like to maintain [slsa-jenkins-generator](https://github.com/Samsung/slsa-jenkins-generator) as an official SLSA project in this organisation.

On https://github.com/slsa-framework/slsa/issues/461 we've had three steering committee members support the donation and tentatively agreed that any project adoptions like this _should_ be approved by a majority of steering committee members.

To that end, this issue will act as a place to collect a vote on moving this specific project into the slsa-framework org (there's a related issue #17 to document the process and expectations as part of the governance documentation here).

@slsa-framework/slsa-steering-committee please comment on this post whether you approve/disapprove of moving slsa-jenkins-generator into the slsa-framework organisation.

cc @HyuckjunChoi

**Comment by trishankatdatadog** [comment]
> @slsa-framework/slsa-steering-committee please comment on this post whether you approve/disapprove of moving slsa-jenkins-generator into the slsa-framework organisation.

Approve

**Comment by joshuagl** [comment]
Approve

**Comment by kimsterv** [comment]
Approve

**Comment by david-a-wheeler** [comment]
It makes sense to me, but since SLSA is an OpenSSF project, it's really a contribution to OpenSSF, correct? If that's correct, approve!

**Comment by joshuagl** [comment]
Thanks for clarifying David.

@HyuckjunChoi could you confirm that you're comfortable with continuing to the OpenSSF under the slsa-framework organisation?

**Comment by david-a-wheeler** [comment]
@HyuckjunChoi - and thank *you* for *your* clarification!! +1 from me!

**Comment by brunodom** [comment]
Approve

**Comment by SaiJyothiGudibandi** [comment]
It would be great if you guys can provide the option to generate salsa2 provenance from Jenkins.

Small request, this feature should be flexible enough to generate provenance for any type of trigger. Not only using Generic Webhook Trigger Plugin.

**Comment by joshuagl** [comment]
We have a majority of steering committee members approving here (plus Mark and Michael on #461), thank you for the contribution @HyuckjunChoi.

Now we just need to figure out the mechanics of transferring the repository to the organisation.

**Comment by joshuagl** [comment]
https://github.com/slsa-framework/slsa-jenkins-generator is now part of the slsa-framework organisation. Thank you for the donation @HyuckjunChoi and Samsung. Look forward to seeing the project evolve.

**Comment by HyuckjunChoi** [comment]
I appreciate a majority of steering committee members approving here and I'm pleased to contribute the slsa-jenkins-generator. We would continue to develop the project.

@SaiJyothiGudibandi Thank you for your comments. We will take your suggestion into consideration.
